# Generated by Django 3.2 on 2023-08-10 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_alter_title_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=12, message='год выпуска не может быть больше текущего'), django.core.validators.MinValueValidator(limit_value=0, message='год выпуска не может отрицательным')], verbose_name='Год'),
        ),
    ]
